sudo: required
dist: trusty

language: node_js
node_js:
    - "6.1"

env:
    global:
        - DBUS_SESSION_BUS_ADDRESS=/dev/null
        - DISPLAY=:99.0
        - CHROME_BIN=chromium-browser

install:
    - npm install

before_script:
    - sh -e /etc/init.d/xvfb start
script:
    - npm run lint